# Generated by Django 4.0.3 on 2022-08-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lastfmuser_api_token_lastfmuser_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('founded_town', models.CharField(max_length=100)),
                ('founded_municipal', models.CharField(max_length=100)),
                ('founded_region', models.CharField(max_length=100)),
                ('founded_country', models.CharField(max_length=100)),
                ('founded_year', models.IntegerField(blank=True)),
                ('birth_date', models.DateField(blank=True)),
                ('genres', models.CharField(max_length=200)),
                ('is_active', models.BooleanField()),
                ('end_year', models.IntegerField(blank=True)),
                ('death_date', models.DateField(blank=True)),
                ('photo_url', models.URLField(default='https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png')),
            ],
        ),
    ]
