# Generated by Django 4.0.3 on 2022-08-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_artist_biography_alter_artist_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='last_fm_link',
            field=models.URLField(default='https://www.last.fm/'),
        ),
    ]
