# Generated by Django 4.0.3 on 2022-08-08 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_artist_last_fm_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='death_date',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='founded_country',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='founded_municipal',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='founded_region',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='founded_town',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='founded_year',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='is_active',
        ),
    ]
